_BASE_: [
  '../datasets/voc.yml',
  '../runtime.yml',
  './_base_/ppyolo_tiny.yml',
  './_base_/optimizer_650e.yml',
  './_base_/ppyolo_tiny_reader.yml',
]

snapshot_epoch: 50
weights: output/ppyolo_tiny_voc/model_final

EvalReader:
  collate_batch: false
